### ISSUE TITLE
Add P3P & P4G Simplified Chinese charsets .tsv supports to BF/BMD File Emulator

### ISSUE THREAD

**Issue by EditorKos** [Sewer56/FileEmulationFramework#22]
Greetings, recently I finished making Simplified Chinese charset tsv files for both P3P and P4G since there are no such ones for Atlus-Script-Tools, I figured might as well provide the files to here, so you can update the BF/BMD File Emulator release with these new charsets.
 
[P3P+P4G_CHS_tsv.zip](https://github.com/user-attachments/files/16596777/P3P%2BP4G_CHS_tsv.zip)

**Comment by Sewer56** [comment]
Would you not want to submit this to
https://github.com/tge-was-taken/Atlus-Script-Tools ?

Any assets like charsets are copied from there during build.
